# Generated by Django 4.0 on 2022-01-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='service',
        ),
    ]
