# Generated by Django 4.0 on 2022-01-08 05:36

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_userprofile_credit_hours_userprofile_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='body',
        ),
        migrations.AddField(
            model_name='service',
            name='capacity',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='service',
            name='picture',
            field=models.ImageField(blank=True, default='uploads/service_pictures/default.png', upload_to='uploads/service_pictures'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_date',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(datetime.date(2022, 1, 8))]),
        ),
        migrations.AddField(
            model_name='service',
            name='service_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
