# Generated by Django 4.0 on 2022-01-08 09:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('social', '0008_alter_service_capacity_alter_service_service_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('isApproved', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('appliedService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.service')),
            ],
        ),
    ]
