# Generated by Django 4.0 on 2022-01-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_serviceapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceapplication',
            old_name='applicationDate',
            new_name='application_date',
        ),
        migrations.RenameField(
            model_name='serviceapplication',
            old_name='appliedService',
            new_name='applied_service',
        ),
        migrations.RenameField(
            model_name='serviceapplication',
            old_name='isApproved',
            new_name='is_approved',
        ),
    ]
