# Generated by Django 4.0 on 2022-01-10 17:41

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('social', '0011_alter_service_service_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(datetime.date(2022, 1, 10))]),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.TextField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('event_date', models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(datetime.date(2022, 1, 10))])),
                ('event_time', models.TimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('picture', models.ImageField(blank=True, default='uploads/event_pictures/default.png', upload_to='uploads/event_pictures/')),
                ('category', models.TextField(blank=True, max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
